{
 "title": "Service Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "HealthCheck",
   "type": "stat",
   "description": "Blackbox healthcheck",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_http_status_code" }
   ]
  },
  {
   "title": "Mysql_UP",
   "type": "graph",
   "description": "Return 1 if database is working",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "No error connections",
   "type": "graph",
   "description": "No error connections percent with database",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - ((sum by (instance) (mysql_global_status_connection_errors_total) - (sum by (instance) (mysql_global_status_connection_errors_total  offset 1m))) / (sum by (instance) (mysql_global_status_connections) - (sum by (instance) (mysql_global_status_connections  offset 1m))) * 100)"
    }
   ]
  },
  {
   "title": "LastLogs",
   "type": "table",
   "description": "Last 10 logs from elastic search",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Oncall errors",
   "type": "stat",
   "description": "The number of Oncall errors over a set period of time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      },
      {
       "field": "1",
       "hide": false,
       "id": "2",
       "pipelineAgg": "1",
       "type": "cumulative_sum"
      }
     ],
     "query": "log.file.path: \"/home/oncall/var/log/uwsgi/error.log\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}