{
 "title": "Node dashboard_imported",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Brief graphics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization brief",
   "type": "heatmap",
   "description": "Percentage of time during which the processor performs work",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(1 - (sum by()(sum by (mode) (node_cpu_seconds_total{mode=\"idle\"}) - sum by (mode) (node_cpu_seconds_total{mode=\"idle\"} offset 1m)) / (sum by () (node_cpu_seconds_total) - sum by () (node_cpu_seconds_total offset 1m)))) * 100"
    }
   ]
  },
  {
   "title": "RAM Usage Brief",
   "type": "heatmap",
   "description": "Percent of used ram in GB",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100"
    }
   ]
  },
  {
   "title": "Used FSM brief",
   "type": "heatmap",
   "description": "Used filesystem memory percent",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "(1 - (node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"})) * 100"
    }
   ]
  },
  {
   "title": "Disk IO count brief",
   "type": "heatmap",
   "description": "Count of IO tasks",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    { "expr": "node_disk_io_now" }
   ]
  },
  {
   "title": "Received bytes brief",
   "type": "heatmap",
   "description": "Count of received bytes in minute",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total - node_network_receive_bytes_total offset 1m"
    }
   ]
  },
  {
   "title": "Transmit bytes brief",
   "type": "heatmap",
   "description": "Count of transmit bytes per minute",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total - node_network_transmit_bytes_total offset 1m"
    }
   ]
  }
 ]
}