---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
remote_write:
  - url: http://victoriametrics:8428/api/v1/write
    queue_config:
      capacity: 2500
      max_shards: 8
      min_shards: 1
      max_samples_per_send: 10000
      batch_send_deadline: 5s
      min_backoff: 30ms
      max_backoff: 5s
      retry_on_http_429: false
rule_files:
  - /etc/prometheus/some_rule.yml
scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    static_configs:
      - targets:
          - localhost:9090
  - job_name: cadvisor
    scrape_interval: 15s
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: custom
    scrape_interval: 15s
    static_configs:
      - targets:
          - custom-exporter:9210
  - job_name: blackbox
    metrics_path: /probe
    params:
      module:
        - http_2xx
    static_configs:
      - targets:
          - oncall:8081
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: oncall
    scrape_interval: 15s
    dns_sd_configs:
      - names:
          - oncall
        type: A
        port: 8081
        
