global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
remote_write:
  - url: http://victoriametrics:8428/api/v1/write
    queue_config:
      capacity: 2500
      max_shards: 8
      min_shards: 1
      max_samples_per_send: 10000
      batch_send_deadline: "5s"
      min_backoff: "30ms"
      max_backoff: "5s"
      retry_on_http_429: false


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s

    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cadvisor'

    scrape_interval: 15s

    static_configs:
      - targets:
          - "'cadvisor:8080'"